# -*- coding: utf-8 -*-
"""app-spam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hdP2tYJ3lCxNurMkMJUnPbpZIXYO6t6u
"""

## Import libraries
import re
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import pickle
import streamlit as st

## Def main function
def main():
    '''
    Loading Preprocessing model
    Loading Naive Bayes model
    '''
    
    #Carregando o modelo
    
    filename = 'clf_naive.pkl'
    clf = pickle.load(open(filename, 'rb'))
    cv = pickle.load(open('tranform_sms.pkl','rb'))
    

    
    st.title('SMS-Detector')
    st.header('Machine learning web app that uses nltk and Naives Bayes Classifier to predict spam SMS')
    message = st.text_area('SMS:', 'Type here:')
    msg = nltk.sent_tokenize(message) 
    stemmer = PorterStemmer() 
    corpus = []
    
    # Preprocessing
    for i in range(len(msg)):
        words = re.sub('[^a-zA-Z]', ' ', msg[i])
        words = words.lower()
        words = words.split()
        words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
        words = ' '.join(words)
        corpus.append(words)
    
    # Predicting
    vect = cv.transform(corpus).toarray()
    predictions = clf.predict(vect)
    
    st.write(predictions)
    
    if st.button('Predict'):
        
        with st.spinner('Analyzing the text …'):
            if predictions.any() == 1:
                st.success("spam")
            
            elif predictions.any() == 0:
                st.success("ham")
            
if __name__ == '__main__':
    main()